[package]
name = "neo-vm-core"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror.workspace = true
num-bigint.workspace = true
num-traits.workspace = true
serde.workspace = true
sha2.workspace = true
sha3.workspace = true
ripemd.workspace = true
hex.workspace = true
